c(F="ofZirs", F="fere}", F="\\EB)", F="yaZr", T="OXFORD JOURNALS", T="oxFoRrpd UnivEerRsity PrRess", 
T="Isolation and Characterization of 115 Street Rabies Virus Isolates from Ethiopia by Using", 
F="Monoclonal Antibodies: Identification of 2 Isolates Mokola and Lagos Bat Viruses", 
"as", "Author(s): Teshome Mebatsion, James H. Cox and Jens W. Frost", 
"Source: The JTournal of Infectious Diseases, Vol. 166, No. 5 (Nov., 1992), 972—977", 
"pp.", "Published by: Oxford University Press", "http://www.jstor.org/stable/301", 
"Stable URL: 13366", "Accessed: 19—10—2017 17:33 UTC", "JTSTOR is a not—for—profit service that helps scholars, researchers, and students discover, use, and build upon a wide", 
"range of content in a trusted digital archive. We use information technology and tools to increase productivity and", 
"facilitate new forms of scholarship. For more information about JTSTOR, please contact support@jstor.org.", 
"Your use of the TSTOR archive indicates your acceptance of the Terms & Conditions of Use, available at", 
"http://about.jstor.org/terms", "& Oxford University Press", 
"is collaborating with JTSTOR to digitize, preserve and extend access", 
"S C‘);( Y to The TJournal of Infectious Diseases", "oi", "(Q", 
"This content downloaded from 169.237.173.120 on Thu, 19 Oct 2017 17:33:07 UTC", 
"All use subject to http://about.jstor.org/terms")
